Prevent RuntimeError
Iterate over a different variable than the one items are removed from
to avoid

```
RuntimeError: dictionary changed size during iteration
```